# Generated by Django 3.2.6 on 2021-08-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
