language: python
dist: xenial
sudo: true

python:
  - 3.9

services:
  postgresql
addons:
  postgresql: '11.5'

env:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: testdb
    ports: ['5432:5432']
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv sync -d
  - cp contrib/env-sample .env

script:
  - pipenv run flake8 .
  - pipenv run pytest --cov=drtimeapi
after_success:
  -pipenv run codecov